# Generated by Django 4.2.5 on 2023-09-23 05:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_alter_products_lessons_alter_products_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='lessonviews',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
            ),
        ),
    ]
